"""Create works and work_chunks tables

Revision ID: 7b54cec44ab6
Revises: 
Create Date: 2024-03-04 19:30:08.502579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b54cec44ab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('embed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_table('work_chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('work_id', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_chunks_id'), 'work_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_chunks_id'), table_name='work_chunks')
    op.drop_table('work_chunks')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    # ### end Alembic commands ###
