"""Create work_citations and work_references tables

Revision ID: 82f1ac62f43f
Revises: 7b54cec44ab6
Create Date: 2024-03-04 19:48:19.031616

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82f1ac62f43f"
down_revision: Union[str, None] = "7b54cec44ab6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_citations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("work_id", sa.Text(), nullable=False),
        sa.Column("citations", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_citations_id"), "work_citations", ["id"], unique=False
    )
    op.create_table(
        "work_references",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("work_id", sa.Text(), nullable=False),
        sa.Column("references", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_references_id"), "work_references", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_references_id"), table_name="work_references")
    op.drop_table("work_references")
    op.drop_index(op.f("ix_work_citations_id"), table_name="work_citations")
    op.drop_table("work_citations")
    # ### end Alembic commands ###
